import Head from "next/head";
import { Inter } from "@next/font/google";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillGithub,
  AiFillLinkedin,
} from "react-icons/ai";
import Image from "next/image";
import deved from "../public/Yash.png";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Yash Patil Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href={`${process.env.NEXT_PUBLIC_FAVICON}/favicon.ico`}
        />
      </Head>
      <main className=" bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" h-screen">
          <nav className=" py-10 mb-12 flex justify-between">
            <h1 className=" text-2xl font-bold font-burtons dark:text-white">
              Yash Patil
            </h1>
            <ul className=" flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl dark:text-white"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                  href="https://drive.google.com/file/d/1_Wxy1x_IShUpZs44kVKVE8lSX5FfE4DT/view?usp=share_link"
                  target="_blank"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className=" text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium md:text-6xl dark:text-teal-400">
              Yash Patil
            </h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">
              Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-gray-200">
              I am a driven and enthusiastic software developer with a passion for creating innovative solutions. As a recent graduate, I have a strong foundation in programming principles and a proven track record of successful projects. I am always looking to expand my skillset and take on new challenges, and I am eager to apply my knowledge and problem-solving abilities to real-world projects. Whether working independently or as part of a team, I am dedicated to delivering high-quality, user-friendly software that meets the needs of clients and end-users. I am excited to start my career and make a positive impact in the world of technology.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <a href="https://twitter.com/YashPat83038421" target="_blank">
              <AiFillTwitterCircle />
            </a>
            <a href="https://github.com/Yash-271120" target="_blank">
              <AiFillGithub />
            </a>
            <a
              href="https://www.linkedin.com/in/yash-patil-3a163519b/"
              target="_blank"
            >
              <AiFillLinkedin />
            </a>
          </div>
          <div className=" relative bg-gradient-to-b from-teal-500 rounded-full overflow-hidden w-52 h-52 sm:w-64 sm:h-64 mt-20 mx-auto md:w-72 md:h-72">
            <Image src={deved} fill objectFit="cover" alt="3D Model of Yash" />
          </div>
        </section>

        <section className=" mt-96">
          <div>
            <div className=" lg:flex gap-10">
              <div className=" text-center shadow-lg p-10 rounded-xl my-10 basis-1/2 dark:bg-gray-400">
                <h3 className="text-4xl sm:text-5xl py-1">Education</h3>
                <div className=" my-4 mt-5">
                  <h5 className="text-xl sm:text-2xl">
                    Indian Institute of Technology (BHU), Varanasi
                  </h5>
                  <h6>B.Tech (Metallurgical Engineering)</h6>
                  <h6>(2019-2023)</h6>
                  <h6 className="text-l sm:text-xl">CGPA - 8.78</h6>
                </div>
                <div className=" my-4">
                  <h5 className="text-xl sm:text-2xl">12th State Board</h5>
                  <h6>(2017-2019)</h6>
                  <h6 className="text-l sm:text-xl">Percentage - 80.15%</h6>
                </div>
                <div className=" my-4">
                  <h5 className="text-xl sm:text-2xl">10th CBSE</h5>
                  <h6>(before 2017)</h6>
                  <h6 className="text-l sm:text-xl">CGPA - 10</h6>
                </div>
              </div>

              <div className=" text-center shadow-lg p-10 rounded-xl my-10 basis-1/2  dark:bg-gray-400">
                <h3 className="text-4xl sm:text-5xl py-1">Experience</h3>
                <h5 className="text-2xl mb-3">
                  Udaan.com Software Engineer Intern (May 2021 - July-2021)
                </h5>
                <a
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 my-20"
                  href="https://udaan.com/about-us"
                  target="_blank"
                >
                  Udaan
                </a>
                <p className=" text-gray-800 w-10/12 mx-auto mt-3 dark:text-black">
                  Udaan is the largest and fastest-growing B2B commerce startup
                  in India. There I worked in a fast paced environment with the
                  warehousing team in{" "}
                  <span className="text-teal-500 dark:text-white">
                    Supply Chain
                  </span>{" "}
                  to directly impact the life of daily users of the product.
                  <p>
                    Developed a solution to{" "}
                    <span className="text-teal-500 dark:text-white">
                      record and track
                    </span>{" "}
                    the time required for various activities performed by human
                    workers in a warehouse environment. Implemented{" "}
                    <span className="text-teal-500 dark:text-white">
                      triggering of events
                    </span>{" "}
                    from the frontend using{" "}
                    <span className="text-teal-500 dark:text-white">react</span>
                    . Integrated with Mixpanel for real-time data analysis.
                  </p>
                  <p>
                    Worked closely with the robot team to establish
                    communication between the warehouse and robotics
                    microservices. Implemented{" "}
                    <span className="text-teal-500 dark:text-white">
                      error handling mechanisms
                    </span>{" "}
                    to ensure smooth and{" "}
                    <span className="text-teal-500 dark:text-white">
                      error-free data transfer
                    </span>{" "}
                    between the two systems, maximizing efficiency and accuracy
                    of warehouse operations.
                  </p>
                </p>
              </div>
            </div>

            <div>
              <div className="text-center shadow-lg p-2 sm:p-10 rounded-xl my-10 ">
                <h3 className="text-4xl sm:text-5xl py-1 dark:text-teal-500">
                  Projects
                </h3>
                <div className="lg:flex">
                  <div className=" text-center dark:border-cyan-500 border-4 sm:border-none sm:shadow-lg p-1 sm:p-10 rounded-xl my-10 mx-5 basis-1/2  dark:bg-gray-400 break-all">
                    <h5 className="text-3xl sm:text-4xl break-normal font-bold mb-3 mx-auto">
                      Woodo
                    </h5>
                    <a
                      className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 my-20"
                      href="https://github.com/Yash-271120/Woodo"
                      target="_blank"
                    >
                      Code
                    </a>
                    <p className=" text-gray-800 w-10/12 break-normal text-left mx-auto mt-3 dark:text-black">
                      <p>
                        • Developed a full-stack e-commerce application using{" "}
                        <span className="text-teal-500 dark:text-white">
                          MERN stack.
                        </span>
                      </p>
                      <br></br>
                      <p>
                        • Designed and built an{" "}
                        <span className="text-teal-500 dark:text-white">
                          intuitive user interface
                        </span>{" "}
                        using React.js for a seamless shopping experience.
                      </p>
                      <br></br>
                      <p>
                        • Utilized Express.js for building{" "}
                        <span className="text-teal-500 dark:text-white">
                          server-side APIs
                        </span>{" "}
                        and integrated with MongoDB for storing application
                        data. Implemented user authentication, product catalog
                        management, shopping cart.
                      </p>
                      <br></br>
                      <p>
                        • Developed a dynamic product catalog management system
                        with the ability to{" "}
                        <span className="text-teal-500 dark:text-white">
                          add, edit, and delete
                        </span>{" "}
                        products. Created a shopping cart system to allow users
                        to add and{" "}
                        <span className="text-teal-500 dark:text-white">
                          manage products in real-time.
                        </span>
                      </p>
                    </p>
                  </div>

                  <div className=" text-center dark:border-cyan-500 border-4 sm:border-none sm:shadow-lg p-1 sm:p-10 rounded-xl my-10 mx-5 basis-1/2  dark:bg-gray-400 break-all">
                    <h5 className="text-3xl sm:text-4xl break-normal font-bold mb-3 mx-auto">
                      E Commerce-Microservices
                    </h5>
                    <a
                      className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 my-20"
                      href="https://github.com/Yash-271120/ecommerce-microservice"
                      target="_blank"
                    >
                      Code
                    </a>
                    <p className=" text-gray-800 break-normal text-left w-10/12 mx-auto mt-3 dark:text-black">
                      <p>
                        • Designed and developed a{" "}
                        <span className="text-teal-500 dark:text-white">
                          scalable e-commerce backend
                        </span>{" "}
                        utilizing{" "}
                        <span className="text-teal-500 dark:text-white">
                          microservices architecture.
                        </span>{" "}
                        Built various microservices for key functionalities such
                        as{" "}
                        <span className="text-teal-500 dark:text-white">
                          user management, product catalog and order management.
                        </span>
                      </p>
                      <br></br>
                      <p>
                        • Implemented{" "}
                        <span className="text-teal-500 dark:text-white">
                          event-driven communication
                        </span>{" "}
                        between microservices using RabbitMQ for efficient data
                        transfer. Utilized{" "}
                        <span className="text-teal-500 dark:text-white">
                          Docker
                        </span>{" "}
                        for containerization.
                      </p>
                    </p>
                  </div>
                </div>

                <div className="lg:flex">
                  <div className=" text-center dark:border-cyan-500 border-4 sm:border-none sm:shadow-lg p-1 sm:p-10 rounded-xl my-10 mx-5 basis-1/2  dark:bg-gray-400 break-all">
                    <h5 className="text-3xl break-normal sm:text-4xl font-bold mb-3 mx-auto">
                      Job Scheduler Backend
                    </h5>
                    <a
                      className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 my-20"
                      href="https://github.com/Yash-271120/JobSchedulerBackend"
                      target="_blank"
                    >
                      Code
                    </a>
                    <p className=" text-gray-800 text-left break-normal w-10/12 mx-auto mt-3 dark:text-black">
                      <p>
                        • Developed a job scheduler backend using{" "}
                        <span className="text-teal-500 dark:text-white">
                          microservices architecture.
                        </span>{" "}
                        Designed and implemented microservices for{" "}
                        <span className="text-teal-500 dark:text-white">
                          job scheduling, execution.
                        </span>{" "}
                        Utilized RabbitMQ for{" "}
                        <span className="text-teal-500 dark:text-white">
                          asynchronous communication between microservices.
                        </span>
                      </p>
                      <br></br>
                      <p>
                        • Implemented a distributed task{" "}
                        <span className="text-teal-500 dark:text-white">
                          queue
                        </span>{" "}
                        using Redis for scheduling and execution. Utilized{" "}
                        <span className="text-teal-500 dark:text-white">
                          Docker
                        </span>{" "}
                        for containerization.
                      </p>
                    </p>
                  </div>

                  <div className=" text-center dark:border-cyan-500 border-4 sm:border-none sm:shadow-lg p-1 sm:p-10 rounded-xl my-10 mx-5 basis-1/2  dark:bg-gray-400 break-all">
                    <h5 className="text-3xl break-normal sm:text-4xl font-bold mb-3 mx-auto">
                      Inventory management frontend
                    </h5>
                    <a
                      className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 my-20"
                      href="https://github.com/Yash-271120/online-thela"
                      target="_blank"
                    >
                      Code
                    </a>
                    <p className=" text-gray-800 break-normal text-left w-10/12 mx-auto mt-3 dark:text-black">
                      <p>
                        • Developed a{" "}
                        <span className="text-teal-500 dark:text-white">
                          user-friendly and responsive
                        </span>{" "}
                        inventory management system frontend using next.js .
                        Implemented real-time updates and optimized the system
                        for{" "}
                        <span className="text-teal-500 dark:text-white">
                          performance and scalability.
                        </span>
                      </p>
                      <br></br>
                      <p>
                        • Designed and implemented various features such as{" "}
                        <span className="text-teal-500 dark:text-white">
                          inventory management(CRUD) and real-time
                          notifications.
                        </span>{" "}
                        Conducted thorough{" "}
                        <span className="text-teal-500 dark:text-white">
                          testing and debugging
                        </span>{" "}
                        to ensure high availability and a smooth user
                        experience.
                      </p>
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section>
          <div className=" text-center p-10 my-10 rounded-xl">
            <h3 className="text-4xl sm:text-5xl py-1 font-bold dark:text-white">
              Skills
            </h3>
            <h6 className=" lg:text-xl dark:text-white text-xs sm:text-l">
              (Always ready to learn more)
            </h6>
            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Languages
              </h5>
              <div className="flex justify-center my-5 mr-5">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 lg:text-xl">
                  JavaScript
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 lg:text-xl">
                  C++
                </div>
              </div>
            </div>

            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Tools
              </h5>
              <div className="flex justify-center my-5 mr-5 flex-wrap gap-6">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Node JS
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  React JS
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Next JS
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Express
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  RabbitMQ
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Redis
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Express
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Tailwindcss
                </div>
              </div>
            </div>

            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Reverse Proxies
              </h5>
              <div className="flex justify-center my-5 mr-5 flex-wrap gap-6">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Ngnix
                </div>
              </div>
            </div>

            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Devops Tools
              </h5>
              <div className="flex justify-center my-5 mr-5 flex-wrap gap-6">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Docker
                </div>
              </div>
            </div>

            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Databases
              </h5>
              <div className="flex justify-center my-5 mr-5 flex-wrap gap-6">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  Mongo DB
                </div>
              </div>
            </div>

            <div>
              <h5 className="text-4xl sm:text-5xl py-5 font-semibold dark:text-white">
                Others
              </h5>
              <div className="flex justify-center my-5 mr-5 flex-wrap gap-6">
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  HTML
                </div>
                <div className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8 mx-5 lg:text-xl">
                  CSS
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
